### ISSUE TITLE
MyData Ontology needs to align with MyData Dictionary from MyData Global

### ISSUE THREAD

**Issue by jimschoening1** [CommonCoreOntology/UserProfileOntology#3]
Interest is growing within MyData Global for both the MyData Dictionary and MyData Ontology.
A prior version of MyData Ontology did align with MyData Dictionary, but the current version does not, so this needs to be resolved.
Since merging the two ontologies would take resources we don't currently have, I suggest we simply switch back to the version that did align, then later merge in additional terms.  What are the Pros and Cons of this?  If this makes sense, who could do this and when?  Does anyone have a copy of the version that did align (since I lost access to my files when I retired)?

**Comment by rockc15** [comment]
I found the my ontology

https://github.com/CommonCoreOntology/my-data-ontology/blob/master/MyDataOntology.ttl

Does this cover the My Data Dictionary

**Comment by jimschoening1** [comment]
And the latest version of MyData Dictionary is at https://dictionary.mydata.org/
I'll ask Anton if he can verify if all the terms from each are covered or if any gaps.

**Comment by jimschoening1** [comment]
My error.  I was looking at the Jane Doe ontology in the Dev file, so I see the actual MyData Ontology does align with MyData Dictionary, with a few terms yet to complete.  As such, I'm closing this issue
